#!/bin/bash

light="#DCBCBC"
light_highlight="#C79999"
mid="#B97C7C"
mid_highlight="#A25050"
dark="#8F2727"
dark_highlight="#7C0000"

gnuplot << END

set terminal postscript enhanced eps color font 'Times-Roman, 25' size 4, 4
set output "area.eps"

unset border

unset xtics
set xrange[-10:10]

unset ytics
set yrange[-10:10]

set samples 100    # X Samples for ++
set isosamples 100  # Y Samples for ++

X(theta) = 3 + 3 * cos( pi * theta / 10.0)
Y(theta) = 3 + 3 * sin( pi * theta / 10.0)

f(x) = x * x * x

plot \
'+' using (X(\$1)):(Y(\$1)) w l lw 3 lc rgb "green" notitle

END

gnuplot << END

set terminal postscript enhanced eps color font 'Times-Roman, 25' size 4, 4
set output "transformed_area.eps"

unset border

unset xtics
set xrange[-10:10]

unset ytics
set yrange[-10:10]

set samples 100    # X Samples for ++
set isosamples 100  # Y Samples for ++

X(theta) = 3 + 3 * cos( pi * theta / 10.0)
Y(theta) = 3 + 3 * sin( pi * theta / 10.0)

alpha = 5
f(x) = log( (pi + 2 * atan(alpha * x)) / (pi - 2 * atan(alpha * x)) )

plot \
'+' using (f(X(\$1))):(f(Y(\$1))) w l lw 3 lc rgb "green" notitle

END
